### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by mayhaps-perchance**
## Introduction

This PR implements some general fixes, like

- removing redundant and invalid _ConVar_ overrides;
- renaming certain aliases to avoid occluding *ConCommands*; and
- updating launch options.

## Rationale

You may verify the accuracy of my claims by inspecting the game binaries for client version 2.2.2.6.

### Aliases

Custom aliases `help` (`core_aliases.cfg`) occludes the existing eponymous *ConCommand*. Custom alias `red` (`core_crosshair.cfg`) occludes the eponymous server-side command. The config should probably avoid aliasing over existing commands unless necessary. 

### *ConVars*

Setting launch options `-useforcedmparms -noforcemaccel -noforcemspd` makes all subsequent changes to mouse-acceleration _ConVars_ redundant (though it might be nice to keep the redundancy anyway). _ConVar_ `m_pitch` is also server-bounded to $\pm 0.022$ unless `sv_cheats` is $1$. `cl_clearhinthistory` is a _ConCommand_ and irrelevant since the config disables player hints. `cl_predictweapons` controls network interpolation and so would better belong in `core_network.cfg` rather than `core_client.cfg`.

### Launch options

*Left 4 Dead 2* ignores launch options `-noforcemparms` and `-nojoy` as of client version 2.2.2.6 (and possibly earlier). Existing options `-noforcemaccel` and `-noforcemspd` require `-useforcedmparms` and are otherwise ignored. Setting *ConVar* `precache_all_survivors` requires cheats, so `sv_cheats` must enabled at some point before setting `precache_all_survivors`.

### CODE REVIEW

**Comment by theletterjwithadot** [comment]
Hi hfmkwi,

I appreciate you taking the time to research further and clear up redundant things in the config.
Besides some consistency issues, I agree with most of the changes that you have made here.

Do let me know if you have any other changes coming or if this PR is ready to be merged!

PS: sorry about the marking as ready and then back to draft

Cheers!
J.

**Comment by mayhaps-perchance** [comment]
Thank you for the feedback 😄 

Addressing the consistency issues, I know that the `red_` crosshair alias deviates from the others’ naming scheme, but I’m unsure of what to rename it to. The _ConCommand_ that the original alias obscured has undocumented behavior that I need to inspect, and the config might be able to safely occlude it if it has no apparent side effects. I’d appreciate it if you could notify me of the other consistency issues.

I’ll do a final review of my changes and adjust _ConVars_ if necessary: there are a couple I’d like to check before I finalize the PR.

**Comment by theletterjwithadot** [comment]
Hi hfmkwi,

I have the practice of updating the configuration date in each file to keep track of the changes made on which day. This is a way to track back on when the last time the file was updated.

Here are the updates you can do for the files:

`core_network.cfg`
- Update date to `15.04.2023`

`core_mouse.cfg`
- Remove `m_yaw` too, since technically, it's set to that by default and is barely touched by players.

`core_crosshair.cfg`
- Update date to `16.04.2023`
- Rename alises for consistency:
```
alias "coff"	
alias "cdefault"
alias "cblue"	
alias "ccyan"	
alias "cgreen"	
alias "corange"	
alias "cpurple"	
alias "cred"	
alias "cwhite"	
alias "cyellow"	
```
- Got to update the colors for the cyclecrosshair aliases too
```
alias "cyclecrosshair"			"cyclecrosshair0"
alias "cyclecrosshair0"			"alias cyclecrosshair cyclecrosshair1; cdefault"
alias "cyclecrosshair1"			"alias cyclecrosshair cyclecrosshair2; cblue"
alias "cyclecrosshair2"			"alias cyclecrosshair cyclecrosshair3; ccyan"
alias "cyclecrosshair3"			"alias cyclecrosshair cyclecrosshair4; cgreen"
alias "cyclecrosshair4"			"alias cyclecrosshair cyclecrosshair5; corange"
alias "cyclecrosshair5"			"alias cyclecrosshair cyclecrosshair6; cpurple"
alias "cyclecrosshair6"			"alias cyclecrosshair cyclecrosshair7; cred"
alias "cyclecrosshair7"			"alias cyclecrosshair cyclecrosshair8; cwhite"
alias "cyclecrosshair8"			"alias cyclecrosshair cyclecrosshair9; cyellow"
alias "cyclecrosshair9"			"alias cyclecrosshair cyclecrosshair0; coff"
```

`core_client.cfg`
- Update date to `15.04.2023`

`core_alises.cfg`
- Update date to `19.04.2023`
- I added a few more aliases to the list. Since you're reviewing those, you might as well review these too:
```
alias "bile"		"say_team >>> BOOMER BILE HERE <<<"
alias "kit"		"say_team >>> MEDKIT HERE <<<"
alias "melee"		"say_team >>> MELEE WEAPON HERE <<<"
alias "molo"		"say_team >>> MOLOTOV HERE <<<"
alias "pill"		"say_team >>> PILLS HERE <<<"
alias "pipe"		"say_team >>> PIPE BOMB HERE <<<"
alias "shot"		"say_team >>> ADRENALINE SHOT HERE <<<"

alias "bom"		"say_team >>> BOOMER <<<"
alias "cha"		"say_team >>> CHARGER <<<"
alias "com"		"say_team >>> CLEAR COMMONS <<<"
alias "hun"		"say_team >>> HUNTER <<<"
alias "joc"		"say_team >>> JOCKEY <<<"
alias "smk"		"say_team >>> SMOKER <<<"
alias "tank"		"say_team >>> TANK <<<"
alias "witch"		"say_team >>> WITCH <<<"

alias "back"		"say_team >>> GO BACK. GO BACK. GO BACK. <<<"
alias "cover"		"say_team >>> COVER ME PLEASE <<<"
alias "distract"	"say_team >>> NEED A DISTRACTION <<<"
alias "eat"		"say_team >>> EAT YOUR PILLS NOW <<<"
alias "gogo"		"say_team >>> GO GO GO <<<"
alias "heal"		"say_team >>> NOW IS A GOOD TIME TO HEAL UP <<<"
alias "helpme"		"say_team >>> HELP ME <<<"
alias "hide"		"say_team >>> DON'T GIVE SIGHT. HIDE PLEASE. <<<"
alias "hit"		"say_team >>> BOOMER TRY. SI SAVE IF BOOMER LANDS. <<<"
alias "hold"		"say_team >>> HOLD UP <<<"
alias "pass"		"say_team >>> PASS PILLS PLEASE <<<"
alias "quad"		"say_team >>> QUAD <<<"
alias "save"		"say_team >>> SI SAVE. DON'T GO. <<<"
alias "shoot"		"say_team >>> SHOOT SHOOT SHOOT <<<"
```
Again, thank you for taking the time to review the aliases to ensure they do not cause any possible conflicts.

Cheers!
J.

**Comment by theletterjwithadot** [comment]
Hi hfmkwi,

I'm just checking on how this is going. I'd love to complete the pull request and update the configuration.

Cheers!
J.

**Comment by theletterjwithadot** [comment]
The author appears to be inactive, so I have made the changes directly.
Completed in https://github.com/theletterjwithadot/Ultimate-Config-for-L4D2/commit/af5ddb9df401c64624069b9b507df69eebd756a8

**Pull request closed without merging**
